import './globals.css';
import type { Metadata } from 'next';
import { JetBrains_Mono } from 'next/font/google';
import { getServerSession } from 'next-auth';
import Link from 'next/link';
import Logout from './logout';

const font = JetBrains_Mono({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body className={font.className}>
        <nav>
          {!!session && <Logout />}
          {!session && <Link href="/login">
            <button className='px-6 py-4 rounded-md border border-black bg-slate-400 hover:bg-slate-600'>
              Login
            </button>
            </Link>}
            {!session && <Link href="/register">
            <button className='px-6 py-4 rounded-md border border-black bg-slate-400 hover:bg-slate-600'>
              Register
            </button>
            </Link>}
        </nav>
        {children}
      </body>
    </html>
  );
}
